package com.iswherevivek.sportsball.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey


@Entity
data class Team(
    val idAPIfootball: String,
    val idLeague: String,
    val idSoccerXML: String,
    @PrimaryKey
    val idTeam: String,
    val intFormedYear: String,
    val intLoved: String,
    val intStadiumCapacity: String,
    val strCountry: String,
    val strDescriptionEN: String,
    val strGender: String,
    val strKeywords: String,
    val strLeague: String,
    val strLocked: String,
    val strRSS: String,
    val strSport: String,
    val strStadium: String,
    val strStadiumDescription: String,
    val strStadiumLocation: String,
    val strStadiumThumb: String,
    val strTeam: String,
    val strTeamBadge: String,
    val strTeamBanner: String,
    val strTeamJersey: String,
    val strTeamLogo: String,
    val strTeamShort: String,
//    val strAlternate: String,
    // val strDescriptionCN: Any,
    // val strDescriptionDE: String,
    //    val idLeague2: String,
//    val idLeague3: String,
//    val idLeague4: String,
//    val idLeague5: String,
//    val idLeague6: String,
//    val idLeague7: String,

//    val strKitColour1: String,
//    val strKitColour2: String,
//    val strKitColour3: String,
    //    val strInstagram: String,
//    val strLeague2: String,
//    val strLeague3: String,
//    val strLeague4: String,
//    val strLeague5: String,
//    val strLeague6: String,
//    val strLeague7: String,

//    val strTwitter: String,
//    val strWebsite: String,
//    val strYoutube: String,
    //    val strTeamFanart1: String,
//    val strTeamFanart2: String,
//    val strTeamFanart3: String,
//    val strTeamFanart4: String,
    //    val strDescriptionES: String,
//    val strDescriptionFR: String,
    // val strDescriptionHU: Any,
    //  val strDescriptionIL: Any,
//    val strDescriptionIT: String,
//    val strDescriptionJP: String,
    //  val strDescriptionNL: Any,
//    val strDescriptionNO: String,
    // val strDescriptionPL: Any,
//    val strDescriptionPT: String,
//    val strDescriptionRU: String,
    // val strDescriptionSE: Any,
    //  val strDivision: Any,
//    val strFacebook: String,
)